# Generated by Django 3.1.5 on 2021-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id_no', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.BigIntegerField()),
                ('operation', models.CharField(choices=[('reverse', 'reverse'), ('reverse_word ', 'reverse_word'), ('flip', 'flip'), ('sort', 'sort')], max_length=200)),
                ('new_text', models.TextField()),
            ],
        ),
    ]
